# This is a basic workflow to help you get started with Actions

name: build and deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: jakejarvis/hugo-build-action@v0.85.0
        with:
          args: --minify
      - uses: actions/upload-artifact@master
        with:
          name: website
          path: './public'
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get public files
        uses: actions/download-artifact@v2
        with:
          name: website
      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: public/
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
